package com.hexated

object ApiConstants {
    const val TMDB_API = "https://api.themoviedb.org/3"
    const val ANILIST_API = "https://graphql.anilist.co"
    const val MALSYNC_API = "https://api.malsync.moe"
    const val JIKAN_API = "https://api.jikan.moe/v4"

    object Sources {
        const val TWO_EMBED = "https://www.2embed.cc"
        const val VIDSRC = "https://vidsrc.to"
        const val DREAMFILM = "https://dreamfilmsw.net"
        const val FILMXY = "https://www.filmxy.vip"
        const val KIMCARTOON = "https://kimcartoon.li"
        const val HIANIME = "https://hianime.to"
        const val ANI_WAVE = "https://aniwave.to"
        const val CRUNCHYROLL = "https://beta-api.crunchyroll.com"
        const val KISSKH = "https://kisskh.co"
        const val LING = "https://ling-online.net"
        const val M4UHD = "https://ww1.streamm4u.ws"
        const val REMOTESTREAM = "https://remotestream.cc"
        const val FLIXON = "https://flixon.lol"
        const val SMASHY_STREAM = "https://embed.smashystream.com"
        const val WATCHSOMUCH = "https://watchsomuch.tv"
        const val NINETV = "https://moviesapi.club"
        const val NOWTV = "https://myfilestorage.xyz"
        const val GOKU = "https://goku.sx"
        const val RIDOMOVIES = "https://ridomovies.tv"
        const val EMOVIES = "https://emovies.si"
        const val MULTIMOVIES = "https://multimovies.top"
        const val MULTIMOVIES2 = "https://multimovies.click"
        const val NETMOVIES = "https://netmovies.to"
        const val ALLMOVIELAND = "https://allmovieland.fun"
        const val DOOMOVIES = "https://doomovies.net"
        const val VIDSRCTO = "https://vidsrc.to"
        const val DRAMADAY = "https://dramaday.me"
        const val SHOWFLIX = "https://showflix.lol"
        const val AONEROOM = "https://api3.aoneroom.com"
        const val WATCHCARTOON = "https://www1.watchcartoononline.bz"
        const val MOFLIX = "https://moflix-stream.xyz"
        const val ZOECHIP = "https://zoechip.org"
        const val NEPU = "https://nepu.to"
        const val FDMOVIES = "https://freedrivemovie.com"
        const val UHDMOVIES = "https://uhdmovies.asia"
        const val HDMOVIES4U = "https://hdmovies4u.day"
        const val VEGAMOVIES = "https://vegamovies.ong"
        const val DOTMOVIES = "https://luxmovies.biz"
        const val TVMOVIES = "https://www.tvseriesnmovies.com"
        const val DAHMERMOVIES = "https://odd-bird-1319.zwuhygoaqe.workers.dev"
    }
}
